
package proxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://enset.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Conversion")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Conversion", targetNamespace = "http://enset.ma/", className = "proxy.Conversion")
    @ResponseWrapper(localName = "ConversionResponse", targetNamespace = "http://enset.ma/", className = "proxy.ConversionResponse")
    @Action(input = "http://enset.ma/BanqueService/ConversionRequest", output = "http://enset.ma/BanqueService/ConversionResponse")
    public double conversion(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://enset.ma/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://enset.ma/", className = "proxy.GetCompteResponse")
    @Action(input = "http://enset.ma/BanqueService/getCompteRequest", output = "http://enset.ma/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compteList", targetNamespace = "http://enset.ma/", className = "proxy.CompteList")
    @ResponseWrapper(localName = "compteListResponse", targetNamespace = "http://enset.ma/", className = "proxy.CompteListResponse")
    @Action(input = "http://enset.ma/BanqueService/compteListRequest", output = "http://enset.ma/BanqueService/compteListResponse")
    public List<Compte> compteList();

}
